version: '3.4'

services:
  courseprojectplanner:
    image: ${DOCKER_REGISTRY-}courseprojectplanner
    build:
      context: .
      dockerfile: CourseProjectPlanner/Dockerfile
    ports: 
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=.;Database=CourseProjectDb;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
